### ISSUE TITLE
printed proposal map shows only polygon and pin

### ISSUE THREAD

**Issue by der-john** [liqd/adhocracy3#2321]
In my local setup of Kiezkasse, I enter the detail view of a proposal with a localisation pin.
Then I click on "print".

I expect to see the same map with pin in the print (and print preview) as I saw in the proposal detail view.

Instead, I see only the polygon (dark-grey on light-grey) and the pin, no roads nor buildings.

**Comment by localgrr** [comment]
I believe @xi and I fixed this yesterday ?

**Comment by der-john** [comment]
I tried it out in `2016-05-tb-print-action` - that's what you meant, right? Does it work on your PC?

**Comment by der-john** [comment]
sorry I'm so stupid: I forgot to build scss.

**Comment by der-john** [comment]
unfortunately this still happens. sometimes, only a stripe one the far-right side of the map has the data, sometimes none of it.

**Comment by xi** [comment]
Can not reproduce.

**Comment by der-john** [comment]
Can not reproduce either. Sorry.
